# Generated by Django 5.0.6 on 2024-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='parcela',
            field=models.IntegerField(blank=True),
        ),
    ]
